name: Docker CI/CD

on:
  push:
    branches:
      - master
    paths:
      - '**.ps1'
      - '**/Dockerfile'

env:
  IMAGE_NAME: azdo2ghrepomigrator

jobs:
  # Build the image.
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build the Container Image
        run: docker build . --file ./Docker/Dockerfile --tag $IMAGE_NAME

      - name: Extract image as Artifact
        run: docker save --output ExtractedImage.tar $IMAGE_NAME

      - name: Publish image as Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ContainerImage
          path: ExtractedImage.tar

  # Push image to Docker Hub
  push:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Download image from Artifacts
        uses: actions/download-artifact@v1
        with:
          name: ContainerImage

      - name: Restore image
        run: docker load --input ContainerImage/ExtractedImage.tar

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            
      - name: Tag the image with run number
        run: docker tag $IMAGE_NAME ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$GITHUB_RUN_NUMBER
            
      - name: Tag the image with latest
        run: docker tag $IMAGE_NAME ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
        
      - name: Push image to Docker Hub (Run Number)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$GITHUB_RUN_NUMBER	
        
      - name: Push image to Docker Hub (Latest)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
