# This ACTION validates the PowerShell scripts
name: Validate PowerShell

on:
  push:
    branches:
      - master
    paths:
      - '**.ps1'
  pull_request:
    paths:
      - '**.ps1'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate PowerShell
        uses: devblackops/github-action-psscriptanalyzer@master
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          failOnErrors: true
          failOnWarnings: false
          failOnInfos: false
