# This ACTION validates the PowerShell scripts
name: ValidatePS

on:
  push:
    branches: 
      - master
    paths:
      - '**.ps1'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate PowerShell
      uses: devblackops/github-action-psscriptanalyzer@master
      with:
        sendComment: false 
